{
  canTriggerIfUnavailable: true,
  checkType: 'general',
  checkAndAct() {},
  methods: {
    _mixinCorSocietyConfig() {
      if (!window.corSociety) {
        return
      }
      if (window.corSociety._mixinCorSocietyConfigVersion === '1.1.322') {
        return
      }
      Object.assign(window.corSociety, {
        logLimit: 240,
        historyPageSize: 8,
        wardrobeLookGroup: 'cor_society_wardrobe',
        vanillaPortraitAssets: {
                  'icons/characters/female.svg': 'img/female.f707fe58.svg',
                  'icons/characters/female_baby.svg': 'img/female_baby.80ac0b1b.svg',
                  'icons/characters/female_old.svg': 'img/female_old.aeab9bd9.svg',
                  'icons/characters/female_teen.svg': 'img/female_teen.94f13bb5.svg',
                  'icons/characters/male.svg': 'img/male.9a3a017c.svg',
                  'icons/characters/male_baby.svg': 'img/male_baby.32e231b9.svg',
                  'icons/characters/male_old.svg': 'img/male_old.c89a5bac.svg',
                  'icons/characters/male_teen.svg': 'img/male_teen.7ca5358d.svg',
                  'icons/characters/roman/auburn/female/adult.svg': 'img/adult.eaeb7ef5.svg',
                  'icons/characters/roman/auburn/female/baby.svg': 'img/baby.3774c082.svg',
                  'icons/characters/roman/auburn/female/old.svg': 'img/old.f1172f25.svg',
                  'icons/characters/roman/auburn/female/teen.svg': 'img/teen.ace18308.svg',
                  'icons/characters/roman/auburn/male/adult.svg': 'img/adult.186b1435.svg',
                  'icons/characters/roman/auburn/male/baby.svg': 'img/baby.dca7baee.svg',
                  'icons/characters/roman/auburn/male/old.svg': 'img/old.98233ad6.svg',
                  'icons/characters/roman/auburn/male/teen.svg': 'img/teen.2c3d4382.svg',
                  'icons/characters/roman/black/female/adult.svg': 'img/adult.8bed277b.svg',
                  'icons/characters/roman/black/female/baby.svg': 'img/baby.a0131621.svg',
                  'icons/characters/roman/black/female/old.svg': 'img/old.5646bd45.svg',
                  'icons/characters/roman/black/female/teen.svg': 'img/teen.bb5d18a0.svg',
                  'icons/characters/roman/black/male/adult.svg': 'img/adult.a82907d8.svg',
                  'icons/characters/roman/black/male/baby.svg': 'img/baby.b5d50f2b.svg',
                  'icons/characters/roman/black/male/old.svg': 'img/old.192ba1c1.svg',
                  'icons/characters/roman/black/male/teen.svg': 'img/teen.cc5a3167.svg',
                  'icons/characters/roman/blonde/female/adult.svg': 'img/adult.f3b985c6.svg',
                  'icons/characters/roman/blonde/female/baby.svg': 'img/baby.64dcb1f6.svg',
                  'icons/characters/roman/blonde/female/old.svg': 'img/old.85bf0ff5.svg',
                  'icons/characters/roman/blonde/female/teen.svg': 'img/teen.f8472117.svg',
                  'icons/characters/roman/blonde/male/adult.svg': 'img/adult.8005b37d.svg',
                  'icons/characters/roman/blonde/male/baby.svg': 'img/baby.6a7f3799.svg',
                  'icons/characters/roman/blonde/male/old.svg': 'img/old.87edf76a.svg',
                  'icons/characters/roman/blonde/male/teen.svg': 'img/teen.ee0167f6.svg',
                  'icons/characters/roman/brown/female/adult.svg': 'img/adult.59b000f2.svg',
                  'icons/characters/roman/brown/female/baby.svg': 'img/baby.9fbb91ff.svg',
                  'icons/characters/roman/brown/female/old.svg': 'img/old.1c61dc78.svg',
                  'icons/characters/roman/brown/female/teen.svg': 'img/teen.2e7738dc.svg',
                  'icons/characters/roman/brown/male/adult.svg': 'img/adult.8a6ed9f9.svg',
                  'icons/characters/roman/brown/male/baby.svg': 'img/baby.1d8786e8.svg',
                  'icons/characters/roman/brown/male/old.svg': 'img/old.adb54f1d.svg',
                  'icons/characters/roman/brown/male/teen.svg': 'img/teen.71ef4800.svg',
                  'icons/characters/roman/brown_curly/female/adult.svg': 'img/adult.3b93dc6a.svg',
                  'icons/characters/roman/brown_curly/female/baby.svg': 'img/baby.cc70ced5.svg',
                  'icons/characters/roman/brown_curly/female/old.svg': 'img/old.9bcd6b91.svg',
                  'icons/characters/roman/brown_curly/female/teen.svg': 'img/teen.cf57a6f7.svg',
                  'icons/characters/roman/brown_curly/male/adult.svg': 'img/adult.87b4f6e9.svg',
                  'icons/characters/roman/brown_curly/male/baby.svg': 'img/baby.fc4eb68f.svg',
                  'icons/characters/roman/brown_curly/male/old.svg': 'img/old.46b580d0.svg',
                  'icons/characters/roman/brown_curly/male/teen.svg': 'img/teen.ed01254f.svg',
                  'icons/characters/roman/dusky/female/adult.svg': 'img/adult.126d7721.svg',
                  'icons/characters/roman/dusky/female/baby.svg': 'img/baby.0a48ceaa.svg',
                  'icons/characters/roman/dusky/female/old.svg': 'img/old.79d0435f.svg',
                  'icons/characters/roman/dusky/female/teen.svg': 'img/teen.e082b316.svg',
                  'icons/characters/roman/dusky/male/adult.svg': 'img/adult.f27497db.svg',
                  'icons/characters/roman/dusky/male/baby.svg': 'img/baby.c7e78900.svg',
                  'icons/characters/roman/dusky/male/old.svg': 'img/old.fb022009.svg',
                  'icons/characters/roman/dusky/male/teen.svg': 'img/teen.21c5438d.svg',
                  'icons/characters/roman/hazel/female/adult.svg': 'img/adult.bd668851.svg',
                  'icons/characters/roman/hazel/female/baby.svg': 'img/baby.1a9b89b4.svg',
                  'icons/characters/roman/hazel/female/old.svg': 'img/old.73d0e21f.svg',
                  'icons/characters/roman/hazel/female/teen.svg': 'img/teen.69563d5c.svg',
                  'icons/characters/roman/hazel/male/adult.svg': 'img/adult.a832d2ed.svg',
                  'icons/characters/roman/hazel/male/baby.svg': 'img/baby.491b5337.svg',
                  'icons/characters/roman/hazel/male/old.svg': 'img/old.2d782b29.svg',
                  'icons/characters/roman/hazel/male/teen.svg': 'img/teen.fcd006f8.svg',
                  'icons/characters/roman/olive/female/adult.svg': 'img/adult.3ed0c1b2.svg',
                  'icons/characters/roman/olive/female/baby.svg': 'img/baby.429f032d.svg',
                  'icons/characters/roman/olive/female/old.svg': 'img/old.408fef7d.svg',
                  'icons/characters/roman/olive/female/teen.svg': 'img/teen.01310b64.svg',
                  'icons/characters/roman/olive/male/adult.svg': 'img/adult.da4471a2.svg',
                  'icons/characters/roman/olive/male/baby.svg': 'img/baby.b825b044.svg',
                  'icons/characters/roman/olive/male/old.svg': 'img/old.89dedfc1.svg',
                  'icons/characters/roman/olive/male/teen.svg': 'img/teen.e75b34c1.svg',
                  'icons/characters/roman/red/female/adult.svg': 'img/adult.c3dbcbe6.svg',
                  'icons/characters/roman/red/female/baby.svg': 'img/baby.100e8154.svg',
                  'icons/characters/roman/red/female/old.svg': 'img/old.2d4a6287.svg',
                  'icons/characters/roman/red/female/teen.svg': 'img/teen.79bc1ad5.svg',
                  'icons/characters/roman/red/male/adult.svg': 'img/adult.e50e6182.svg',
                  'icons/characters/roman/red/male/baby.svg': 'img/baby.3ce59ad9.svg',
                  'icons/characters/roman/red/male/old.svg': 'img/old.eaebff03.svg',
                  'icons/characters/roman/red/male/teen.svg': 'img/teen.ddc1b1e8.svg',
                  'icons/characters/roman/tan/female/adult.svg': 'img/adult.3d0c21d8.svg',
                  'icons/characters/roman/tan/female/baby.svg': 'img/baby.5a264e0c.svg',
                  'icons/characters/roman/tan/female/old.svg': 'img/old.439bc75d.svg',
                  'icons/characters/roman/tan/female/teen.svg': 'img/teen.c726315b.svg',
                  'icons/characters/roman/tan/male/adult.svg': 'img/adult.87a69f29.svg',
                  'icons/characters/roman/tan/male/baby.svg': 'img/baby.2bfbf42d.svg',
                  'icons/characters/roman/tan/male/old.svg': 'img/old.aee50a51.svg',
                  'icons/characters/roman/tan/male/teen.svg': 'img/teen.93a4a950.svg'
                },
        stratumOrder: ['senatorial', 'equestrian', 'civic', 'plebeian', 'freedmen', 'poor'],
        strata: {
                  senatorial: {
                    title: 'Senatorial Houses',
                    singular: 'senatorial house',
                    min: 4,
                    basePrestige: [80000, 180000],
                    heritage: ['roman_patrician', 'roman_novus_homo'],
                    jobs: ['senator', 'lawyer', 'rhetor'],
                    traits: ['senator', 'ambitious', 'oratorDeliberative'],
                    cost: 2500,
                    support: 400,
                    revenue: 120
                  },
                  equestrian: {
                    title: 'Equestrian Houses',
                    singular: 'equestrian house',
                    min: 5,
                    basePrestige: [25000, 80000],
                    heritage: ['roman_novus_homo', 'roman_plebeian'],
                    jobs: ['trader', 'lawyer', 'physician'],
                    traits: ['educated', 'competitive', 'gregarious'],
                    cost: 1400,
                    support: 260,
                    revenue: 90
                  },
                  civic: {
                    title: 'Civic Citizens',
                    singular: 'civic family',
                    min: 5,
                    basePrestige: [8000, 25000],
                    heritage: ['roman_plebeian', 'roman_novus_homo'],
                    jobs: ['lawyer', 'physician', 'rhetor', 'painter'],
                    traits: ['literate', 'content', 'trusting'],
                    cost: 700,
                    support: 150,
                    revenue: 55
                  },
                  plebeian: {
                    title: 'Plebeian Citizens',
                    singular: 'plebeian family',
                    min: 5,
                    basePrestige: [1500, 8000],
                    heritage: ['roman_plebeian'],
                    jobs: ['trader', 'painter', 'labourer'],
                    traits: ['content', 'gregarious', 'charitable'],
                    cost: 350,
                    support: 85,
                    revenue: 35
                  },
                  freedmen: {
                    title: 'Freedmen',
                    singular: 'freedman house',
                    min: 4,
                    basePrestige: [500, 5000],
                    heritage: ['roman_freedman'],
                    jobs: ['trader', 'painter', 'labourer'],
                    traits: ['literate', 'greedy', 'trusting'],
                    cost: 220,
                    support: 55,
                    revenue: 25
                  },
                  poor: {
                    title: 'Slaves',
                    singular: 'slave kin group',
                    min: 4,
                    basePrestige: [0, 1200],
                    heritage: ['roman_plebeian', 'roman_freedman'],
                    jobs: ['labourer', null],
                    traits: ['content', 'charitable', 'stubborn'],
                    cost: 120,
                    support: 30,
                    revenue: 12
                  }
                },
        nomina: ['Aelius', 'Aemilius', 'Antonius', 'Appius', 'Atilius', 'Calpurnius', 'Cassius', 'Claudius', 'Cornelius', 'Fabius', 'Flavius', 'Fulvius', 'Julius', 'Licinius', 'Livius', 'Marcius', 'Marius', 'Minucius', 'Octavius', 'Pompeius', 'Porcius', 'Quinctius', 'Sergius', 'Sulpicius', 'Valerius'],
        cognomina: ['Afer', 'Agricola', 'Balbus', 'Caldus', 'Cato', 'Corvus', 'Crispus', 'Felix', 'Flaccus', 'Longus', 'Magnus', 'Naso', 'Niger', 'Paullus', 'Rufus', 'Severus', 'Varro', 'Vetus'],
        maleNames: ['Aulus', 'Caeso', 'Decimus', 'Gaius', 'Gnaeus', 'Lucius', 'Manius', 'Marcus', 'Numerius', 'Publius', 'Quintus', 'Servius', 'Sextus', 'Spurius', 'Titus', 'Tiberius'],
        femaleNames: ['Aelia', 'Aemilia', 'Antonia', 'Appia', 'Atilia', 'Calpurnia', 'Cassia', 'Claudia', 'Cornelia', 'Fabia', 'Flavia', 'Fulvia', 'Julia', 'Licinia', 'Livia', 'Marcia', 'Octavia', 'Pompeia', 'Porcia', 'Valeria'],
        crestFields: ['crimson', 'vermilion', 'madder', 'purple', 'indigo', 'sea', 'cypress', 'black', 'umber', 'ochre', 'marble'],
        crestMetals: ['gold', 'bronze', 'silver', 'bone', 'copper'],
        crestAccents: ['gold', 'bronze', 'silver', 'bone', 'crimson', 'purple', 'indigo', 'cypress', 'black', 'ochre'],
        crestShapes: ['scutum', 'oval', 'round', 'vexillum', 'kite', 'hex'],
        crestDivisions: ['plain', 'pale', 'fess', 'bend', 'bendSinister', 'quartered', 'chief', 'chevron', 'saltire', 'orle'],
        crestPatterns: ['none', 'dots', 'bars', 'waves', 'rays', 'tiles'],
        crestCharges: ['spqr', 'aquila', 'laurel', 'thunderbolt', 'standard', 'column', 'sun', 'crescent', 'star', 'scales', 'ship', 'spear', 'tower', 'hand'],
        crestBorders: ['simple', 'double', 'bossed', 'laurel', 'rivets'],
        crestMarks: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'X', 'XII', 'SPQR'],
        crestPalette: {
                  crimson: '#8f1f22',
                  vermilion: '#b93a28',
                  madder: '#6f1628',
                  purple: '#5c2d63',
                  indigo: '#263f73',
                  sea: '#1f6771',
                  cypress: '#2f5f45',
                  black: '#202026',
                  umber: '#6b3f24',
                  ochre: '#b67b2d',
                  marble: '#ded8c8',
                  gold: '#d6aa3c',
                  bronze: '#a56635',
                  silver: '#d8dde1',
                  bone: '#eee0c4',
                  copper: '#c87545'
                },
        romanRoads: ['the Via Sacra', 'the Via Appia', 'the Via Latina', 'the Via Flaminia', 'the Via Aurelia', 'the Via Ostiensis', 'the Via Salaria', 'the Via Tiburtina', 'the Clivus Capitolinus', 'the Vicus Tuscus', 'the Argiletum', 'the Vicus Iugarius', 'the Clivus Argentarius'],
        romanDistricts: ['the Subura', 'the Velabrum', 'the Forum Boarium', 'the Forum Holitorium', 'the Campus Martius', 'the Velia', 'the Carinae', 'the Vicus Patricius', 'the Argiletum', 'Trans Tiberim'],
        romanHills: ['the Palatine', 'the Aventine', 'the Caelian', 'the Esquiline', 'the Viminal', 'the Quirinal', 'the Capitoline', 'the Janiculum'],
        romanLandmarks: ['the Forum Romanum', 'the Theatre of Pompey', 'the Circus Maximus', 'the Tiber wharves', 'the Aemilian warehouses', 'the Porticus Aemilia', 'the salt works at Ostia', 'the Emporium docks'],
        romanRegions: ['Latium', 'Campania', 'Etruria', 'Umbria', 'Samnium', 'Apulia', 'Picenum', 'Sicilia', 'Sardinia', 'Hispania', 'Gallia Cisalpina', 'Africa', 'Achaea', 'Asia'],
        romanEstateLocations: ['an estate on the Palatine', 'a townhouse in the Subura', 'a warehouse by the Emporium docks', 'a workshop along the Argiletum', 'a villa in Campania', 'farmland in Latium', 'an insula near the Forum Boarium', 'orchards on the Caelian', 'vineyards in Etruria', 'a granary at Ostia', 'a tannery in Trans Tiberim', 'a horrea on the Aventine']
      })
      window.corSociety._mixinCorSocietyConfigVersion = '1.1.322'
    }
  }
}
